<?php

/* 
 * The bid18xxSubmit page is called from an email generated by
 * bid18xxStart. This page accepts and verifies the player's 
 * bid and then updates the database. It then checks to see
 * if all players have submitted their bids. If they have then
 * it reports the bid results to each player. 
 * 
 * This page's URL should contain a urlkey parameter. This is
 * a 12 character pseudo random string that begins with the
 * bidid and the playerid. 
 * 
 * Copyright (c) 2020 Richard E. Price under the The MIT License.
 * A copy of this license can be found in the LICENSE.text file.
 */

$urlkey = filter_input(INPUT_GET, 'urlkey',FILTER_SANITIZE_STRING);
$bidid  = intval(substr($urlkey,0,4));
$playerid  = intval(substr($urlkey,4,1));

?>
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>BID18xx - Player Order Bid Tool For 18xx Games</title>
    <link rel="shortcut icon" href="images/favicon.ico" >
    <link rel="stylesheet" href="style/bid18xxCom.css" />
    <link rel="stylesheet" href="style/bid18xxSubmit.css" />
    <script type="text/javascript" src="scripts/jquery.js">
    </script> 
    <script type="text/javascript" src="scripts/bid18xxCom.js">
    </script>
    <script type="text/javascript" src="scripts/bid18xxConfig.js">
    </script>
    <script type="text/javascript" src="scripts/bid18xxSubmit.js">
    </script>
    <script>
      $(function() {
        $('.error').hide();
        BID18.errtxt = "";
        BID18.input = [];
        BID18.input.urlkey = '<?php echo "$urlkey"; ?>';
        BID18.input.bidid = parseInt(<?php echo "$bidid"; ?>);
        BID18.input.playerid = parseInt(<?php echo "$playerid"; ?>);
        $('#bid').append(BID18.input.bidid).append('.');
        var cString = "bidid=" + BID18.input.bidid;
        $.post("php/getBid.php", cString, getBidResult);
       
        $("#button1").on("click",function(){
          processBid();
          return false;          
        }); // end button1 click
        $("#button2").on("click",function(){
          window.location.assign("bid18xxGoodby.html?msgtype=0");
          return false;          
        }); // end button2 click 
        $("#button3").on("click",function(){
          window.location.assign("bid18xxGoodby.html?msgtype=0");
          return false;          
        }); // end button3 click 
        $("#button4").on("click",function(){
          var recallnext = 'bid18xxSubmit.php?bidid=';
          recallnext += BID18.input.bidid + '&playerid=';
          recallnext += BID18.input.playerid;
          window.location.assign(recallnext);
          return false;          
        }); // end button4 click  
        $("#button5").on("click",function(){
          window.location.assign("bid18xxGoodby.html?msgtype=0");
          return false;          
        }); // end button5 click 
      });
    </script>
  </head>
  <body>
  
    <div id="topofpage">
      <div id="logo">
        <img src="images/logo.png" alt="Logo"/> 
      </div>
      <div id="heading">
        <h1>BID18xx</h1>
        <h1>The Player Order Bid Tool For 18xx Games</h1>
      </div>
    </div>
    <div id="restofpage"> 
      <div id="content">
        <div id="toptext">
          <p id="pid">
            Hello   
          </p>
          <p id="bid">
            The bid id for this bid session is  
          </p>
        </div>
        <div id="bidrpt">
        </div>
        <div id="playerorder">
        </div>
        <div id="bidform" class="allforms">
          Be sure to select your bid before you press enter!<br>
          <form name="form1" action="" >
            <p> Bid:
              <input type="radio" id="b0" name="bid" 
                     value=0 checked>
              <label for="b0">$0</label>
              <input type="radio" id="b5" name="bid" 
                     value=5>   
              <label for="b5">$5</label>
              <input type="radio" id="b10" name="bid" 
                     value=10>
              <label for="b10">$10</label>
            </p>
            <input type="button" name="button1" class="pwbutton" 
                   id="button1" value="Enter" >
            <input type="button" name="button2" class="pwbutton" 
                   id="button2" value="Cancel" >
          </form>
        </div>
        <div id="canform" class="allforms">
          <form name="form2" action="" >
            <input type="button" name="button3" class="pwbutton" 
                   id="button3" value="Cancel" >
          </form>
        </div>        
        <div id="collform" class="allforms"><p id="collp">
          Your update collided with another player's update.<br>
          Try again. If you get this message repeatedly then 
          contact the BID18xx webmaster<br><br></p>
          <form name="form5" action="" >
            <input type="button" name="button4" class="pwbutton" 
                   id="button4" value="Retry" >
            <input type="button" name="button5" class="pwbutton" 
                   id="button5" value="Cancel" >
          </form>
        </div>
      </div>  
    </div>  

  </body>
</html>



